name: Scan docker image
permissions: read-all

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  docker-image-security-scan:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v3.3.0

      - name: ☁️ Download latest image
        run: docker pull postgres:14

      - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'json'
          output: 'docker-security-scan.json.tmp'
          image-ref: 'postgres:latest'
          #github-pat: ${{ secrets.GITHUB_TOKEN }} # or ${{ secrets.github_pat_name }} if you're using a PAT

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "/etc/passwd"
      
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo "It exists !"
  
